name: Miloš Pallo, FIIT STU v Bratislave
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

title: Osobná stránka, Miloš Pallo
email: milos159@gmail.com
description: >
  Volám sa Miloš Pallo. Toto je moja osobnostná stránka na GitHub Pages. Som študent
  informatiky na Fakulte informatiky a informačných technológií na STU v Bratislave.
url: "_milos159.github.io"
github_username:  milos159

